p8105_hw1_daq2107.Rmd
================
Diego A. Quintana Licona (daq2107)
2026-09-23

## Loading necessary libraries for this assignment:

``` r
library(tidyverse)
```

    ## Warning: package 'readr' was built under R version 4.5.2

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.0     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.2     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.1     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Problem 1

Loading ‘penguins’ data set:

``` r
data("penguins", package = "palmerpenguins")
```

After the data has been loaded, we can explore the ‘penguins’ data set:

``` r
penguins #General observation of the data frame.
```

    ## # A tibble: 344 × 8
    ##    species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
    ##    <fct>   <fct>              <dbl>         <dbl>             <int>       <int>
    ##  1 Adelie  Torgersen           39.1          18.7               181        3750
    ##  2 Adelie  Torgersen           39.5          17.4               186        3800
    ##  3 Adelie  Torgersen           40.3          18                 195        3250
    ##  4 Adelie  Torgersen           NA            NA                  NA          NA
    ##  5 Adelie  Torgersen           36.7          19.3               193        3450
    ##  6 Adelie  Torgersen           39.3          20.6               190        3650
    ##  7 Adelie  Torgersen           38.9          17.8               181        3625
    ##  8 Adelie  Torgersen           39.2          19.6               195        4675
    ##  9 Adelie  Torgersen           34.1          18.1               193        3475
    ## 10 Adelie  Torgersen           42            20.2               190        4250
    ## # ℹ 334 more rows
    ## # ℹ 2 more variables: sex <fct>, year <int>

``` r
nrow(penguins) #Obtaining number of rows
```

    ## [1] 344

``` r
ncol(penguins) #Obtaining number of columns
```

    ## [1] 8

``` r
#To obtain the mean value of the flipper length, we use the pull function and remove the missing values using 'na.rm':
mean(pull(penguins, flipper_length_mm), na.rm = TRUE)
```

    ## [1] 200.9152

``` r
sd(pull(penguins, flipper_length_mm), na.rm = TRUE)
```

    ## [1] 14.06171

``` r
#Also analyzing bill length, since this is an important variable that we will be analyzing:
mean(pull(penguins, bill_length_mm), na.rm = TRUE)
```

    ## [1] 43.92193

``` r
sd(pull(penguins, bill_length_mm), na.rm = TRUE)
```

    ## [1] 5.459584

``` r
#Using inline R code below...
```

**Description (using inline R code):** We see that the ‘penguins’ data
set is a tibble containing 344 observations and 8 variables. Each
observation corresponds to a penguin, whereas the variables describe
their location (categorical ‘island’ variable), their species
(categorical), sex (categorical), year (numeric), and physical
characteristics of each penguin, including their bills’ length and depth
(millimeters; numeric), their flippers’ length (millimeters; numeric),
and overall body mass (grams; numeric).

Additionally, after removing missing values (using ‘na.rm’) we see that
the mean flipper length for all observations in the data set is
200.9152047 mm, with a standard deviation of 14.0617137 mm.

Moreover, after removing missing values we see that the mean bill length
for all observations in the data set is 43.9219298 mm, with a standard
deviation of 5.4595837 mm.

**Visualizing the data**

We can also create a scatter plot of flipper length (y) vs. bill length
(x). Note that ggplot automatically removes NA values when creating the
scatter plot:

``` r
#Using ggplot (part of 'tidyverse' package). Note that ggplot automatically removes NA values from scatter plot:

ggplot(penguins, aes(x = bill_length_mm, 
                     y = flipper_length_mm,
                     color = species)) +  #Coloring per 'species' variable
    geom_point() +
  
#Adding labels to my scatter plot (I know this code syntax per previous experience with ggplot in another class and work)
  
  labs(title = "Penguin Flipper Length vs. Bill Length",
       x = "Bill Length (mm)",
       y = "Flipper Length (mm)",
       color = "Penguin Species") +
  
  theme(plot.title = element_text(hjust = 0.5)) #Centering my title
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_daq2107_files/figure-gfm/scatter_plot_penguins-1.png)<!-- -->

``` r
#Saving my plot using 'ggsave':

ggsave(filename = "DSI_HW1_Problem1.jpg")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

## Problem 2

We can create a data frame using the ‘tibble’ function (part of the
‘tidyverse’ package):

``` r
set.seed(0) #Setting seed to make sure you are getting the same output as me

new_df = tibble(
  vec_sample = rnorm(10, mean = 1), #Random sample of 10 and mean equal to 1
  vec_log = vec_sample > 0, #Logical vector checking if the sample's elements are above zero
  vec_char = c("This", "is", "my", "ten", "character", "vector", "with", "great", "joy", "woohoo!"), #Character vector
  vec_factor = factor(c("Mexican", "Japanese", "Japanese", "Mexican", "Lebanese", "Lebanese", "Mexican", "Mexican", "Lebanese", "Japanese")) #Factor vector with three nationality levels
)
```

After we have created our desired data frame, we can attempt to take the
mean of each newly-created vector variable:

``` r
mean(pull(new_df, vec_sample))
```

    ## [1] 1.358924

``` r
mean(pull(new_df, vec_log))
```

    ## [1] 0.9

``` r
mean(pull(new_df, vec_char))
```

    ## Warning in mean.default(pull(new_df, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(new_df, vec_factor))
```

    ## Warning in mean.default(pull(new_df, vec_factor)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

We can see from the output above that we are able to take the mean for
our random sample (mean = 1.36) and logical vectors (mean = 0.9; since
it is taking Boolean values to be either ‘1’ or ‘0’ for TRUE or FALSE,
respectively). Thus, what happens is that we are able to take the mean
for the logical and random sample vectors. However, what doesn’t work is
taking the means of the character and factor vector since they do not
contain numerical elements.

Per the assignment instructions, we can attempt to use the ‘as.numeric’
function to convert the variables into numerical variables and then take
the mean:

``` r
#Observing my vectors converted using 'as.numeric':
as.numeric(pull(new_df, vec_log))
as.numeric(pull(new_df, vec_char))
```

    ## Warning: NAs introduced by coercion

``` r
as.numeric(pull(new_df, vec_factor))
```

**Consider that the following description is based on the output I was
able to observe. However, per the assignment instructions, the final
version of this RMarkdown does not show the code chunk output (removed
using ‘results = hide’):**

What happens from using the code above is that the ‘as.numeric’ function
converts the vector elements into numerical elements. This works for the
logical and factor vectors, but not for the character vector. The
logical vector elements converted into numeric 1 or 0 (values
corresponding to ‘TRUE’ and ‘FALSE’, respectively) and the factor vector
elements to numeric 1, 2, or 3 values (corresponding to each of the
three categorical levels). This explains what we saw when we took the
mean above: Boolean elements get converted to 1 or 0, whereas the factor
elements turn from categorical variables (which we cannot take the mean
from) to numerical 1, 2, and 3 from which we can now take the mean.
However, the character vector values still remain as ‘NA’, and thus
can’t still take the mean. We confirm this with the message ‘Warning:
NAs introduced by coercion’. This makes sense since there is no
standardized logic or order for character elements to convert them to
numerical elements.

## The End :) Have a wonderful day!
